### Test de la route racine
GET http://localhost:3000/

###############################################
# BOOKS ROUTES
###############################################

### Récupère la liste des livres
GET http://localhost:3000/api/books/

### Récupère les livres disponibles
GET http://localhost:3000/api/books/available/2

### Récupère tous les livres (endpoint alternatif)
GET http://localhost:3000/api/books/all

### Récupère le livre avec l'ID 1
GET http://localhost:3000/api/books/1

### Création d'un livre
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "Nouveau Livre",
    "authorId": 8,
    "year": 2024
}

### Modification d'un livre
PUT http://localhost:3000/api/books/11
Content-Type: application/json

{
    "id": 11,
    "title": "Voilà un meilleur titre MDFK",
    "year": 2024
}

### Suppression d'un livre
DELETE http://localhost:3000/api/books/2

###############################################
# AUTHORS ROUTES
###############################################

### Récupère la liste des auteurs
GET http://localhost:3000/api/authors

### Récupère un auteur de par son id
GET http://localhost:3000/api/authors/4

### Création d'un auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "birth_year": 1961,
    "nationality": "American"
}

### Modification de l'auteur (id 8)
PUT http://localhost:3000/api/authors/8
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "nationality": "American"
}

### Suppression d'un auteur
DELETE http://localhost:3000/api/authors/1

###############################################
# LOANS ROUTES
###############################################
### Récupère la liste des prêts
GET http://localhost:3000/api/loans

### Créer un nouvel emprunt
POST http://localhost:3000/api/loans
Content-Type: application/json

{
    "book_id": 1,
    "borrower_name": "Patrick l'étoile de mer",
    "borrowed_date": "2026-01-07",
    "return_date": "2026-02-27"
}

### // Récupérer un emprunt par son ID
GET http://localhost:3000/api/loans/16

### // Mettre à jour un emprunt (retour de livre)
PUT http://localhost:3000/api/loans/1
Content-Type: application/json

{
    "borrower_name": "Patrick l'étoile de mer",
    "loan_status": "returned",
    "return_date": "2026-04-15"
}

### // Mettre à jour un emprunt (retour de livre)
PATCH http://localhost:3000/api/loans/1
Content-Type: application/json

{
    "borrower_name": "Itler Adolf",
    "loan_status": "returned",
    "return_date": ""
}

### // Supprimer un emprunt (retour de livre)
DELETE http://localhost:3000/api/loans/4

### // Supprimer tous les emprunts
DELETE http://localhost:3000/api/loans

###############################################
# AUTH
###############################################
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "testUser",
    "password": "123"
}

###############################################
# DEV ROUTES
###############################################
### Route de test SQL
GET http://localhost:3000/all

### Vérification de l'intégrité référentielle des auteurs
GET http://localhost:3000/api/authors/verify