### Test de la route racine
GET http://localhost:3000/

### Création d'un auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "birth_year": 1802,
    "nationality": "French"
}

### Création d'un livre
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "Nouveau Livre",
    "authorId": 8,
    "year": 2024
}

### Récupère la liste des livres
GET http://localhost:3000/api/books

### Récupère la liste des auteurs
GET http://localhost:3000/api/authors

### Récupère un auteur de par son id
GET http://localhost:3000/api/authors/8

### Met à jour l'auteur avec l'ID 8
PUT http://localhost:3000/api/authors/8
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "nationality": "American"
}

### Récupère tous les livres (endpoint alternatif)
GET http://localhost:3000/api/books/all

### Récupère le livre avec l'ID 6
GET http://localhost:3000/api/books/6
