### Test de la route racine
GET http://localhost:3000/

###############################################
# BOOKS ROUTES
###############################################

### Récupère la liste des livres
GET http://localhost:3000/api/books

### Récupère tous les livres (endpoint alternatif)
GET http://localhost:3000/api/books/all

### Récupère le livre avec l'ID 6
GET http://localhost:3000/api/books/6

### Création d'un livre
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title": "Nouveau Livre",
    "authorId": 8,
    "year": 2024
}

### Modification d'un livre
PUT http://localhost:3000/api/books/11
Content-Type: application/json

{
    "id": 11,
    "title": "Voilà un meilleur titre MDFK",
    "year": 2024
}

### Suppression d'un livre
DELETE http://localhost:3000/api/books/2

###############################################
# AUTHORS ROUTES
###############################################

### Récupère la liste des auteurs
GET http://localhost:3000/api/authors

### Récupère un auteur de par son id
GET http://localhost:3000/api/authors/8

### Création d'un auteur
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "birth_year": 1961,
    "nationality": "American"
}

### Modification de l'auteur (id 8)
PUT http://localhost:3000/api/authors/8
Content-Type: application/json

{
    "firstName": "Barak",
    "lastName": "Obama",
    "nationality": "American"
}

### Suppression d'un auteur
DELETE http://localhost:3000/api/authors/1